spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: backdend

gcp:
  credentials:
    path: src\main\resources\credentials\googleCredentils.json
  bucket:
    name: blog-media-bucket
