spring.application.name=idn-news


# spring.config.import=application-dev.properties, application-prod.properties
# spring.profiles.active=dev


# PostgreSQL DB Configuration
spring.datasource.url=jdbc:postgresql://ep-lucky-block-ameei7qa-pooler.c-5.us-east-1.aws.neon.tech/idn_news?user=neondb_owner&password=npg_tGvMSx2fuE7g&sslmode=require&channelBinding=require
spring.datasource.username=postgres
spring.datasource.password=Imhound@101
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true

spring.sendgrid.api-key="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"
app.verify.url=http://localhost:8080/public/api/v1/signup/verify

# Logging Configuration
logging.level.org.springframework=INFO
logging.level.com.idndefence=DEBUG

logging.pattern.console=${LOGGER_PATTERN_CONSOLE:%green(%d{HH:mm:ss}) %red(%-5level) %blue([%thread]) %yellow(%logger{15}) - %msg%n}

server.port=${PORT:8080}

# # Development Tools
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=true
# spring.main.lazy-initialization=true

# #TomCat Configuration
# server.tomcat.threads.max=10
# server.tomcat.threads.min-spare=2

spring.threads.virtual.enabled=true
# management.endpoints.access.default=NONE