spring.application.name=idn-news
server.port=${SERVER_PORT:8080}
spring.threads.virtual.enabled=true
springdoc.swagger-ui.enabled=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.devtools.restart.enabled=false


# spring.profiles.active=${SPRING_PROFILE:prod}


# PostgreSQL DB Configuration
spring.datasource.url=${SPRING_DB_URL:jdbc:postgresql://localhost:5432/idn_news}
spring.datasource.username=${SPRING_DB_USER:postgres}
spring.datasource.password=${SPRING_DB_PWD:Imhound@101}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true


# Sendgrid Config
spring.sendgrid.api-key=${SENDGRID_API_KEY:"Dummy"}

#Email Verification address
app.verify.url=${APP_VERIFY_URL:http://localhost:8080/public/api/v1/signup/verify}



# GCP config
gcp.credentials.path=${GCP_CRED_PATH:src/main/resources/credentials/googleCredentils.json}
gcp.bucket.name=${GCP_BUCKET_NAME:blog-media-bucket}


# Mail Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your@gmail.com
spring.mail.password=zifd rqbn xfrk xzvj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
