spring.application.name=idn-news


spring.config.import=application-dev.properties, application-prod.properties
# spring.profiles.active=dev


# PostgreSQL DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/idn_news
spring.datasource.username=postgres
spring.datasource.password=Imhound@101
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true

app.verify.url=http://localhost:8080/public/api/v1/signup/verify

server.port=8082


spring.threads.virtual.enabled=true
springdoc.swagger-ui.enabled=true




